server:
  port: 8080
spring:
  datasource:
    username: root
    password: testtest
    url:
      jdbc:mysql://localhost:3306/search_engine?useSSL=false&requir
      eSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatement=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: none
    show-sql: false
  sql:
    init:
      mode: always


indexing-settings:
  sites:
    - url: https://volochek.life/
      name: Volochek
    - url: https://dombulgakova.ru/
      name: Dombulgakova
    - url: http://cimus.biz
      name: Cimus
    - url: https://nikoartgallery.com/
      name: Nikoartgallery
    - url: http://www.playback.ru/
      name: Playback
  user-agent: GockSearchBot
  referrer: http://www.google.com